name: Build Hardened Docker Image

on:
  push:
    branches:
      - main
      - imagehardening-assignment
  pull_request:
    branches:
      - main
      - imagehardening-assignment

jobs:
  build-hardened-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # Optional: Login to DockerHub if you want to push the image later 
      - name: Login to DockerHub (optional)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Hardened Docker Image
        run: |
          docker build -t hardened-python-app:latest .

      - name: Run container to verify
        run: |
          docker run --rm hardened-python-app:latest id

      - name: Output workflow steps as table
        run: |
          echo "| Step Name                     | Description                                      |" >> $GITHUB_STEP_SUMMARY
          echo "|------------------------------|-------------------------------------------------|" >> $GITHUB_STEP_SUMMARY
          echo "| Checkout code                | Checks out repository code                        |" >> $GITHUB_STEP_SUMMARY
          echo "| Set up Docker Buildx         | Sets up Docker Buildx for advanced builds         |" >> $GITHUB_STEP_SUMMARY
          echo "| Login to DockerHub (optional)| Logs in to DockerHub if credentials are present   |" >> $GITHUB_STEP_SUMMARY
          echo "| Build Hardened Docker Image  | Builds the Docker image with hardening            |" >> $GITHUB_STEP_SUMMARY
          echo "| Run container to verify      | Runs the built image to verify it works           |" >> $GITHUB_STEP_SUMMARY
