name: Container Image Scan

on:
  push:
    branches: [main, imagescan-assignment]
  pull_request:
    branches: [main, imagescan-assignment]

jobs:
  image-vulnerability-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t devsecops-python-app:latest .

      - name: Scan image with Snyk
        uses: snyk/actions/docker@master
        with:
          image: devsecops-python-app:latest
          args: >
            --json-file-output=results/snyk-report.json
            --sarif-file-output=results/snyk-report.sarif
            --severity-threshold=low
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Snyk JSON report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-json-report
          path: results/snyk-report.json

      - name: Upload Snyk SARIF report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-sarif-report
          path: results/snyk-report.sarif

      - name: Print Summary in Logs
        run: |
          echo "Snyk Scan Complete. Vulnerability summary below:"
          cat results/snyk-report.json | jq '.vulnerabilities[] | {severity, title, packageName}' || echo "No vulnerabilities found"
