name: Build Hardened Docker Image

on:
  push:
    branches: [imagehardening-assignment]
  pull_request:
    branches: [main]

jobs:
  build-hardened-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub (optional)
        if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Hardened Docker Image
        run: |
          docker build -t hardened-python-app:latest .

      - name: Run container to verify
        run: |
          docker run --rm hardened-python-app:latest id
