name: Python Snyk Scan + SBOM Analysis (Docker)

on:
  push:
    branches:
      - main
      - sca-pipeline
  pull_request:
    branches:
      - main
      - sca-pipeline

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Run Snyk CLI Docker container to test Python dependencies
      - name: Run Snyk test for Python dependencies
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e SNYK_TOKEN=${{ secrets.SNYK_TOKEN }} \
            snyk/snyk:docker test --file=requirements.txt
        continue-on-error: false

      - name: Install Syft & Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM with Syft
        run: syft dir:. -o json > sbom.json

      - name: Scan SBOM with Grype
        run: grype sbom:sbom.json -o table

      # Upload SBOM to Snyk using Docker image
      - name: Upload SBOM to Snyk
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e SNYK_TOKEN=${{ secrets.SNYK_TOKEN }} \
            snyk/snyk:docker monitor --sbom-file=sbom.json
          