name: Python Snyk Scan + SBOM Analysis (Docker)

on:
  push:
    branches: [main, sca-pipeline]
  pull_request:
    branches: [main, sca-pipeline]

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Snyk Python test (via Docker)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -e SNYK_TOKEN=${{ secrets.SNYK_TOKEN }} \
            snyk/snyk:docker \
            test --file=requirements.txt --package-manager=pip --fail-on=all
        continue-on-error: false

      - name: Install Syft & Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM with Syft
        run: syft dir:. -o json > sbom.json

      - name: Scan SBOM with Grype
        run: grype sbom:sbom.json -o table

      - name: Upload SBOM to Snyk (via pip CLI)
        run: |
          pip install snyk
          snyk sbom upload sbom.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
