name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage pytest-cov

      - name: Run tests and generate coverage report
        run: |
          coverage run -m pytest tests/
          coverage xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v5
        with:
          args: >
            -Dsonar.projectKey=Iam-anirudhdeshmukh_DevSecOps-Assignment
            -Dsonar.organization=Iam-anirudhdeshmukh
            -Dsonar.branch.name=main
            -Dsonar.sources=.
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.host.url=https://sonarcloud.io
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


